---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: play-dev
  namespace: default
  selfLink: "/apis/extensions/v1beta1/namespaces/default/deployments/play-dev"
  uid: 394b350f-1ea5-11e8-8bf3-080027819c80
  resourceVersion: '6428'
  generation: 9
  creationTimestamp: '2018-03-03T05:39:21Z'
  labels:
    k8s-app: play-dev
  annotations:
    deployment.kubernetes.io/revision: '8'
spec:
  replicas: 7
  selector:
    matchLabels:
      k8s-app: play-dev
  template:
    metadata:
      name: play-dev
      creationTimestamp: 
      labels:
        k8s-app: play-dev
    spec:
      containers:
      - name: play-dev
        image: 10.0.2.2:8086/frontend:35
        resources: {}
        terminationMessagePath: "/dev/termination-log"
        terminationMessagePolicy: File
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 9
  replicas: 7
  updatedReplicas: 7
  readyReplicas: 7
  availableReplicas: 7
  conditions:
  - type: Available
    status: 'True'
    lastUpdateTime: '2018-03-05T03:16:17Z'
    lastTransitionTime: '2018-03-05T03:16:17Z'
    reason: MinimumReplicasAvailable
    message: Deployment has minimum availability.
  - type: Progressing
    status: 'True'
    lastUpdateTime: '2018-03-05T04:26:22Z'
    lastTransitionTime: '2018-03-03T05:39:21Z'
    reason: NewReplicaSetAvailable
    message: ReplicaSet "play-dev-64f96c8c59" has successfully progressed.
