---
# vim: ft=yaml
version: '2'
services:
  jenkins:
    build:
      context: .
      args:
        - HOST_DOCKER_GROUPID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"

  registry:
    image: registry
    ports:
      - "8082:5000"
