# vim: ft=yaml
---
version: '2'
services:
  jenkins:
    build:
      context: .
      args:
        - HOST_DOCKER_GROUPID
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_network
  registry:
    image: registry
    ports:
      - "8086:5000"
    networks:
      - jenkins_network
  registry_frontend:
    image: joxit/docker-registry-ui:static
    environment:
      - REGISTRY_URL=http://registry:5000
    ports:
      - "8082:80"
    networks:
      - jenkins_network
networks:
  jenkins_network:
